<b>Given a bank customer, build a neural network-based classifier that can determine whether they will leave or not in the next 6 months.</b> Perform the following steps:
- Read the dataset
- Distinguish feature and target set and divide the dataset into training and testing sets
- Normalize train and test data
- Initialize and build the model. Identify points of improvement and print accuracy and confusion matrix

Import dependencies

In [ ]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

import tensorflow as tf

Read dataset from csv

In [1]:
df = pd.read_csv('Churn_Modelling.csv')
df.head()

NameError: name 'pd' is not defined

Check for null values

In [36]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

Separating feature and target sets

In [37]:
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

print("X: ")
print(df.iloc[:, 3:-1])
print("Y: ")
print(df.iloc[:, -1])

X: 
      CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0       

Encoding data

In [38]:
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2]) # Gender Column 0: Female and 1: Male
print(X[2])

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print("\n", X[2])

[502 'France' 0 42 8 159660.8 3 1 0 113931.57]

 [1.0 0.0 0.0 502 0 42 8 159660.8 3 1 0 113931.57]


In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print(X_train, len(X_train))
print()
print(y_train, len(y_train))
print("-"*40)
print(X_test, len(X_test))
print()
print(y_test, len(y_test))

[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]] 8000

[0 0 0 ... 0 0 1] 8000
----------------------------------------
[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [0.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]] 2000

[0 1 0 ... 0 0 0] 2000


Feature Scaling

In [40]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print(X_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


Creating the ANN

In [42]:
ann = tf.keras.models.Sequential() 
# For stack of layers where each layer has one input and one output tensor
# Sequential API allows creation of models Layer by layer. Other one is functional

Adding input layer and first hidden layer

In [43]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

Addiing the second hidden layer

In [44]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

Adding the output layer

In [45]:
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

Compiling the ANN

In [46]:
ann.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [47]:
ann.fit(X_train, y_train, batch_size=32, epochs=200)

Epoch 1/200
250/250 [==============================] - 1s 1ms/step - loss: 0.6744 - accuracy: 0.6159
Epoch 2/200
250/250 [==============================] - 0s 1ms/step - loss: 0.5139 - accuracy: 0.7960
Epoch 3/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4823 - accuracy: 0.7960
Epoch 4/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4558 - accuracy: 0.7968
Epoch 5/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4292 - accuracy: 0.8062
Epoch 6/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4103 - accuracy: 0.8185
Epoch 7/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3965 - accuracy: 0.8306
Epoch 8/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3848 - accuracy: 0.8382
Epoch 9/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3753 - accuracy: 0.8435
Epoch 10/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3683 - accura

250/250 [==============================] - 1s 2ms/step - loss: 0.3266 - accuracy: 0.8652
Epoch 161/200
250/250 [==============================] - 1s 2ms/step - loss: 0.3274 - accuracy: 0.8640
Epoch 162/200
250/250 [==============================] - 1s 2ms/step - loss: 0.3278 - accuracy: 0.8668
Epoch 163/200
250/250 [==============================] - 1s 2ms/step - loss: 0.3268 - accuracy: 0.8673
Epoch 164/200
250/250 [==============================] - 1s 2ms/step - loss: 0.3272 - accuracy: 0.8646
Epoch 165/200
250/250 [==============================] - 1s 2ms/step - loss: 0.3272 - accuracy: 0.8649
Epoch 166/200
250/250 [==============================] - 1s 2ms/step - loss: 0.3270 - accuracy: 0.8655
Epoch 167/200
250/250 [==============================] - 1s 2ms/step - loss: 0.3274 - accuracy: 0.8637
Epoch 168/200
250/250 [==============================] - 1s 2ms/step - loss: 0.3271 - accuracy: 0.8675
Epoch 169/200
250/250 [==============================] - 1s 2ms/step - loss: 0.3270 - a

Testing the model

In [48]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [49]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1517   78]
 [ 200  205]]


0.861